### ISSUE TITLE
Show warning if user has selected public repository instead private for storing notes

### ISSUE THREAD

**Issue by vivekweb2013** [git-noter/gitnoter#49]
There is no restriction on using a public repository for storing notes. But user should be prompted with a warning saying the repository is public and their notes could be accessible publicly when they choose to use a public repo for storing notes.

This is is requires only frontend changes.

**Comment by omegaui** [comment]
@vivekweb2013 

Take a look at [GitHub's Rest API](https://docs.github.com/en/rest/repos) to obtain the JSON codec list of public repositories.

**Comment by vivekweb2013** [comment]
@omegaui the type of repository is already there in gitnoter repositories response payload. This ticket is about showing the warning on UI if the user selects public repository.

**Comment by omegaui** [comment]
> @omegaui the type of repository is already there in gitnoter repositories response payload. This ticket is about showing the warning on UI if the user selects public repository.

I noticed that already,
I don't know go that much to contribute code,
Just wanted to tell the starting point.
Anyways awesome project.

**Comment by vivekweb2013** [comment]
Done
