### ISSUE TITLE
Text input elements from editor are not visible in dark mode

### ISSUE THREAD

**Issue by spartan4cs** [git-noter/gitnoter#65]
**Describe the bug**
Dark theme is  giving a problem. add the option to change back to light 

**Screenshots**
![image](https://user-images.githubusercontent.com/23625985/172045716-8df679da-9efc-457d-97b7-fe6b2b52f2d3.png)

**Please provide browser information:**
chrome

**Comment by vivekweb2013** [comment]
@src-hyc thanks so much. It looks pretty good now 👍 

@spartan4cs Hope this works for you!
